ERROR - 2025-06-07 14:14:22 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `se...', 0)
#1 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `se...')
#2 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `se...')
#3 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `se...', Array, false)
#4 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\wamp64\www\aditi-service\app\Controllers\Admin\Service.php(93): CodeIgniter\Model->insert(Array)
#8 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Admin\Service->save_service()
#9 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Service))
#10 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\aditi-service\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\aditi-service\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-07 14:14:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: admin/services/save-service]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `services` (`user_id`, `service_name`, `project_id`, `website_url`, `whatsapp_number`, `created_at`, `updated_at`) VALUES (:user_id:, :service_name:, :project_id:, :website_url:, :whatsapp_number:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Admin\Service.php(93): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Service->save_service()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Service))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-07 14:14:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `services` (`user_id`, `service_name`, `project_id`, `website_url`, `whatsapp_number`, `created_at`, `updated_at`) VALUES (\'1\', \'App Development\', \'#app123\', \'https://chatgpt.com/c/68442e32-48a4-8008-9403-b4c6b7be2ce3\', \'9876543210\', \'2025-06-07 14:14:22\', \'2025-06-07 14:14:22\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `services` (`user_id`, `service_name`, `project_id`, `website_url`, `whatsapp_number`, `created_at`, `updated_at`) VALUES (\'1\', \'App Development\', \'#app123\', \'https://chatgpt.com/c/68442e32-48a4-8008-9403-b4c6b7be2ce3\', \'9876543210\', \'2025-06-07 14:14:22\', \'2025-06-07 14:14:22\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `services` (`user_id`, `service_name`, `project_id`, `website_url`, `whatsapp_number`, `created_at`, `updated_at`) VALUES (:user_id:, :service_name:, :project_id:, :website_url:, :whatsapp_number:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Admin\Service.php(93): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Service->save_service()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Service))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-07 14:14:22 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `services` (`user_id`, `service_name`, `project_id`, `website_url`, `whatsapp_number`, `created_at`, `updated_at`) VALUES (\'1\', \'App Development\', \'#app123\', \'https://chatgpt.com/c/68442e32-48a4-8008-9403-b4c6b7be2ce3\', \'9876543210\', \'2025-06-07 14:14:22\', \'2025-06-07 14:14:22\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `services` (`user_id`, `service_name`, `project_id`, `website_url`, `whatsapp_number`, `created_at`, `updated_at`) VALUES (\'1\', \'App Development\', \'#app123\', \'https://chatgpt.com/c/68442e32-48a4-8008-9403-b4c6b7be2ce3\', \'9876543210\', \'2025-06-07 14:14:22\', \'2025-06-07 14:14:22\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `services` (`user_id`, `service_name`, `project_id`, `website_url`, `whatsapp_number`, `created_at`, `updated_at`) VALUES (\'1\', \'App Development\', \'#app123\', \'https://chatgpt.com/c/68442e32-48a4-8008-9403-b4c6b7be2ce3\', \'9876543210\', \'2025-06-07 14:14:22\', \'2025-06-07 14:14:22\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `services` (`user_id`, `service_name`, `project_id`, `website_url`, `whatsapp_number`, `created_at`, `updated_at`) VALUES (:user_id:, :service_name:, :project_id:, :website_url:, :whatsapp_number:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Admin\Service.php(93): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Service->save_service()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Service))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-07 14:33:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Updates are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: admin/edit-user]
in SYSTEMPATH\Model.php on line 456.
 1 SYSTEMPATH\BaseModel.php(1031): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Admin\AdminHome.php(187): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\AdminHome->edit_user()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\AdminHome))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
